name: CI-RELEASE

on:
  push:
    branches:
      - main

jobs:
  ci-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install standard-version
        run: yarn add standard-version

      - name: Generate changelog and release
        run: yarn release
