name: CI-TESTING

on: [pull_request]

jobs:
  ci-testing:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile

      - name: Validate unit tests
        run: yarn test
